name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: install package.json
      run: npm install
    
    - name: Run Test1
      run: |
        output=$(node dist/Test1.js)
        exit_code=$output

        if [ $exit_code -ne 0 ]; then
          echo "Error $exit_code"
          exit 1
        fi
